/*!
 * Ext JS Library 3.0+
 * Copyright(c) 2006-2009 Ext JS, LLC
 * licensing@extjs.com
 * http://www.extjs.com/license
 */
// some data used in the examples
Ext.namespace('Ext.countrydata');

Ext.countrydata.countries = [
        ['AF', 'Afghanistan'],
		['AX', 'Aland Islands'],
		['AL', 'Albania'],
		['DZ', 'Algeria'],
		['AS', 'American Samoa'],
		['AD', 'Andorra'],
		['AO', 'Angola'],
		['AI', 'Anguilla'],
		['AQ', 'Antarctica'],
		['AG', 'Antigua and Barbuda'],
		['AR', 'Argentina'],
		['AM', 'Armenia'],
		['AW', 'Aruba'],
		['AU', 'Australia'],
		['AT', 'Austria'],
		['AZ', 'Azerbaijan'],
		['BS', 'Bahamas'],
		['BH', 'Bahrain'],
		['BD', 'Bangladesh'],
		['BB', 'Barbados'],
		['BY', 'Belarus'],
		['BE', 'Belgium'],
		['BZ', 'Belize'],
		['BJ', 'Benin'],
		['BM', 'Bermuda'],
		['BT', 'Bhutan'],
		['BO', 'Bolivia'],
		['BA', 'Bosnia and Herzegovina'],
		['BW', 'Botswana'],
		['BV', 'Bouvet Island'],
		['BR', 'Brazil'],
		['BQ', 'British Antarctic Territory'],
		['IO', 'British Indian Ocean Territory'],
		['VG', 'British Virgin Islands'],
		['BN', 'Brunei'],
		['BG', 'Bulgaria'],
		['BF', 'Burkina Faso'],
		['BI', 'Burundi'],
		['KH', 'Cambodia'],
		['CM', 'Cameroon'],
		['CA', 'Canada'],
		['CT', 'Canton and Enderbury Islands'],
		['CV', 'Cape Verde'],
		['KY', 'Cayman Islands'],
		['CF', 'Central African Republic'],
		['TD', 'Chad'],
		['CL', 'Chile'],
		['CN', 'China'],
		['CX', 'Christmas Island'],
		['CC', 'Cocos (Keeling) Islands'],
		['CO', 'Colombia'],
		['KM', 'Comoros'],
		['CG', 'Congo (Brazzaville)'],
		['CD', 'Congo (Kinshasa)'],
		['CK', 'Cook Islands'],
		['CR', 'Costa Rica'],
		['HR', 'Croatia'],
		['CU', 'Cuba'],
		['CY', 'Cyprus'],
		['CZ', 'Czech Republic'],
		['DK', 'Denmark'],
		['DJ', 'Djibouti'],
		['DM', 'Dominica'],
		['DO', 'Dominican Republic'],
		['NQ', 'Dronning Maud Land'],
		['DD', 'East Germany'],
		['TL', 'East Timor'],
		['EC', 'Ecuador'],
		['EG', 'Egypt'],
		['SV', 'El Salvador'],
		['GQ', 'Equatorial Guinea'],
		['ER', 'Eritrea'],
		['EE', 'Estonia'],
		['ET', 'Ethiopia'],
		['FK', 'Falkland Islands'],
		['FO', 'Faroe Islands'],
		['FJ', 'Fiji'],
		['FI', 'Finland'],
		['FR', 'France'],
		['GF', 'French Guiana'],
		['PF', 'French Polynesia'],
		['TF', 'French Southern Territories'],
		['FQ', 'French Southern and Antarctic Territories'],
		['GA', 'Gabon'],
		['GM', 'Gambia'],
		['GE', 'Georgia'],
		['DE', 'Germany'],
		['GH', 'Ghana'],
		['GI', 'Gibraltar'],
		['GR', 'Greece'],
		['GL', 'Greenland'],
		['GD', 'Grenada'],
		['GP', 'Guadeloupe'],
		['GU', 'Guam'],
		['GT', 'Guatemala'],
		['GN', 'Guinea'],
		['GW', 'Guinea-Bissau'],
		['GY', 'Guyana'],
		['HT', 'Haiti'],
		['HM', 'Heard Island and McDonald Islands'],
		['HN', 'Honduras'],
		['HK', 'Hong Kong S.A.R., China'],
		['HU', 'Hungary'],
		['IS', 'Iceland'],
		['IN', 'India'],
		['ID', 'Indonesia'],
		['IR', 'Iran'],
		['IQ', 'Iraq'],
		['IE', 'Ireland'],
		['IL', 'Israel'],
		['IT', 'Italy'],
		['CI', 'Ivory Coast'],
		['JM', 'Jamaica'],
		['JP', 'Japan'],
		['JT', 'Johnston Island'],
		['JO', 'Jordan'],
		['KZ', 'Kazakhstan'],
		['KE', 'Kenya'],
		['KI', 'Kiribati'],
		['KW', 'Kuwait'],
		['KG', 'Kyrgyzstan'],
		['LA', 'Laos'],
		['LV', 'Latvia'],
		['LB', 'Lebanon'],
		['LS', 'Lesotho'],
		['LR', 'Liberia'],
		['LY', 'Libya'],
		['LI', 'Liechtenstein'],
		['LT', 'Lithuania'],
		['LU', 'Luxembourg'],
		['MO', 'Macao S.A.R., China'],
		['MK', 'Macedonia'],
		['MG', 'Madagascar'],
		['MW', 'Malawi'],
		['MY', 'Malaysia'],
		['MV', 'Maldives'],
		['ML', 'Mali'],
		['MT', 'Malta'],
		['MH', 'Marshall Islands'],
		['MQ', 'Martinique'],
		['MR', 'Mauritania'],
		['MU', 'Mauritius'],
		['YT', 'Mayotte'],
		['FX', 'Metropolitan France'],
		['MX', 'Mexico'],
		['FM', 'Micronesia'],
		['MI', 'Midway Islands'],
		['MD', 'Moldova'],
		['MC', 'Monaco'],
		['MN', 'Mongolia'],
		['MS', 'Montserrat'],
		['MA', 'Morocco'],
		['MZ', 'Mozambique'],
		['MM', 'Myanmar'],
		['NA', 'Namibia'],
		['NR', 'Nauru'],
		['NP', 'Nepal'],
		['NL', 'Netherlands'],
		['AN', 'Netherlands Antilles'],
		['NT', 'Neutral Zone'],
		['NC', 'New Caledonia'],
		['NZ', 'New Zealand'],
		['NI', 'Nicaragua'],
		['NE', 'Niger'],
		['NG', 'Nigeria'],
		['NU', 'Niue'],
		['NF', 'Norfolk Island'],
		['KP', 'North Korea'],
		['VD', 'North Vietnam'],
		['MP', 'Northern Mariana Islands'],
		['NO', 'Norway'],
		['OM', 'Oman'],
		['QO', 'Outlying Oceania'],
		['PC', 'Pacific Islands Trust Territory'],
		['PK', 'Pakistan'],
		['PW', 'Palau'],
		['PS', 'Palestinian Territory'],
		['PA', 'Panama'],
		['PZ', 'Panama Canal Zone'],
		['PG', 'Papua New Guinea'],
		['PY', 'Paraguay'],
		['YD', 'Peoples Democratic Republic of Yemen'],
		['PE', 'Peru'],
		['PH', 'Philippines'],
		['PN', 'Pitcairn'],
		['PL', 'Poland'],
		['PT', 'Portugal'],
		['PR', 'Puerto Rico'],
		['QA', 'Qatar'],
		['RE', 'Reunion'],
		['RO', 'Romania'],
		['RU', 'Russia'],
		['RW', 'Rwanda'],
		['SH', 'Saint Helena'],
		['KN', 'Saint Kitts and Nevis'],
		['LC', 'Saint Lucia'],
		['PM', 'Saint Pierre and Miquelon'],
		['VC', 'Saint Vincent and the Grenadines'],
		['WS', 'Samoa'],
		['SM', 'San Marino'],
		['ST', 'Sao Tome and Principe'],
		['SA', 'Saudi Arabia'],
		['SN', 'Senegal'],
		['CS', 'Serbia And Montenegro'],
		['SC', 'Seychelles'],
		['SL', 'Sierra Leone'],
		['SG', 'Singapore'],
		['SK', 'Slovakia'],
		['SI', 'Slovenia'],
		['SB', 'Solomon Islands'],
		['SO', 'Somalia'],
		['ZA', 'South Africa'],
		['GS', 'South Georgia and the South Sandwich Islands'],
		['KR', 'South Korea'],
		['ES', 'Spain'],
		['LK', 'Sri Lanka'],
		['SD', 'Sudan'],
		['SR', 'Suriname'],
		['SJ', 'Svalbard and Jan Mayen'],
		['SZ', 'Swaziland'],
		['SE', 'Sweden'],
		['CH', 'Switzerland'],
		['SY', 'Syria'],
		['TW', 'Taiwan'],
		['TJ', 'Tajikistan'],
		['TZ', 'Tanzania'],
		['TH', 'Thailand'],
		['TG', 'Togo'],
		['TK', 'Tokelau'],
		['TO', 'Tonga'],
		['TT', 'Trinidad and Tobago'],
		['TN', 'Tunisi'],
		['TR', 'Turkey'],
		['TM', 'Turkmenistan'],
		['TC', 'Turks and Caicos Islands'],
		['TV', 'Tuvalu'],
		['PU', 'U.S. Miscellaneous Pacific Islands'],
		['VI', 'U.S. Virgin Islands']
       
    ];
