# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1212577273);
user_pref("app.update.lastUpdateTime.background-update-timer", 1212577272);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1212577272);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1212577273);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1212577274);
user_pref("browser.migration.version", 1);
user_pref("browser.places.createdSmartBookmarks", true);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.tabs.forceHide", false);
user_pref("extensions.enabledItems", "langpack-en-GB@xulrunner-1.9.ubuntu.com:1.9b5,langpack-en-GB@firefox-3.0.ubuntu.com:3.0b5,ubufox@ubuntu.com:0.5,{972ce4c6-7e08-4474-a285-3208198ce6fd}:2.0");
user_pref("extensions.lastAppVersion", "3.0b5");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.autoconfig_url", "http://proxy.uwc.ac.za/");
user_pref("network.proxy.type", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1215169276);
