<?php
require_once 'PHPUnit/Framework.php';
require_once(dirname(__FILE__).'/../../config.php');

/**
 * Test class for Pandra.
 * Generated by PHPUnit on 2010-01-09 at 11:52:23.
 */
class PandraCoreTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * To test multiple nodes, add their connection strings here
     *
     * @access protected
     */
    protected function setUp() {
        PandraCore::auto('localhost');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
        PandraCore::disconnect('default');
    }

    /**
     * Get a modes list
     */
    public function testSupportedModes() {
        $modes = PandraCore::getSupportedModes();
        $this->assertTrue(is_array($modes) && !empty($modes));
    }

    /**
     * Set Read Mode
     */
    public function testSetReadMode() {
        $supportedModes = PandraCore::getSupportedModes();
        foreach ($supportedModes as $mode) {
            PandraCore::setReadMode($mode);
            $this->assertEquals(PandraCore::getReadMode(), $mode);
        }
    }

    /**
     * Set Write Mode
     */
    public function testSetWriteMode() {
        $supportedModes = PandraCore::getSupportedModes();
        foreach ($supportedModes as $mode) {
            PandraCore::setWriteMode($mode);
            $this->assertEquals(PandraCore::getWriteMode(), $mode);
        }
    }

    /**
     * Set active node to named 'default', as well as unknown 'NOP'
     */
    public function testSetActiveNode() {

        $tokens = PandraCore::getPoolTokens();
        foreach ($tokens as $token) {
            $this->assertTrue(PandraCore::setActiveNode($token));
        }
        $this->assertFalse(PandraCore::setActiveNode('NOP'));
    }

    /**
     * @todo Implement testDisconnect().
     */
    public function testDisconnect() {
        $tokens = PandraCore::getPoolTokens();
        foreach ($tokens as $token) {
            $this->assertTrue(PandraCore::disconnect($token));
        }
    }

    /**
     * Disconnect all nodes
     */
    public function testDisconnectAll() {
        $this->assertTrue(PandraCore::disconnectAll());
    }

    /**
     * Connect to a good and bad host
     */
    public function testConnect() {
        $this->assertTrue(PandraCore::connect('default', 'localhost'));
        $this->assertFalse(PandraCore::connect('default_BAD', 'ih-opethishostdoesntexist'));
    }

    /**
     * Get client for all supported modes
     */
    public function testGetClient() {
        $supportedModes = PandraCore::getSupportedModes();
        foreach ($supportedModes as $mode) {
            PandraCore::setReadMode($mode);
            $client = PandraCore::getClient();
            $this->assertEquals(get_class($client), 'CassandraClient', "Bad Client (mode $mode)");
        }
    }

    /**
     * Describe a named keyspace
     */
    public function testDescribeKeyspace() {
        return;
        $ks = PandraCore::describeKeyspace('Keyspace1');

        $this->assertTrue(is_array($ks) && !empty($ks));

        // While we don't care about the individual ColumnFamilies, we should
        // at least be able to pull out the default Standard1 CF Cassandra rolls out with
        $expectedKeys = array('CompareWith', 'Type', 'Desc');
        $diff = array_diff($expectedKeys, array_keys($ks['Standard1']));

        $this->assertTrue(empty($diff));
    }

    /**
     * @todo Implement testLoadConfigXML().
     */
    public function testLoadConfigXML() {
        $config = PandraCore::loadConfigXML();
        $this->assertTrue(get_class($config) == 'SimpleXMLElement');
    }

    /**
     * @todo
     */
    public function testGetCFSlice() {
    }

    public function testGetCFSliceMulti() {
    }

    public function testGetCFColumnCount() {
    }

    public function testGetRangeKeys() {
    }

    /**
     * @todo
     */
    public function testDeleteColumnPath() {
    }

    /**
     * @todo
     */
    public function testSaveColumnPath() {
    }

    /**
     * @todo
     */
    public function testSaveSuperColumn() {
    }

    public function getSetConsistency() {

        $newC = cassandra_ConsistencyLevel::QUORUM;

        PandraCore::setConsistency($newC);
        $this->assertTrue(PandraCore::getConsistency() == $newC);
        $this->assertTrue(PandraCore::getConsistency(cassandra_ConsistencyLevel::ONE) == cassandra_ConsistencyLevel::ONE);
    }
}
?>