myJS = 'asfasfas';

/*
function avoir_realtime_base_gwt_Invite(){var l='',B='" for "gwt:onLoadErrorFn"',z='" for "gwt:onPropertyErrorFn"',Eb='"><\/script>',n='/',mb='40A2AE6D6EEA0A60435012CA7E55160D.cache.html',ib='5D66C2EAEDC10F7AB5AB4E6D519A320B.cache.html',jb='6B32365287C34F2F832E08A1FF67D8D6.cache.html',Db='<script id="',Bb="<script>avoir_realtime_base_gwt_Invite.onInjectionDone('avoir.realtime.base.gwt.Invite')<\/script>",v='=',kb='A66CB628E72F5A5821ADBD221FB9BE43.cache.html',y='Bad handler "',lb='D9D1AFC75B33BE5FB494158D88524198.cache.html',wb='DOMContentLoaded',vb='Invite.css',Fb='SCRIPT',Cb='__gwt_marker_avoir.realtime.base.gwt.Invite',m='avoir.realtime.base.gwt.Invite',o='base',q='clear.cache.gif',u='content',db='gecko',eb='gecko1_8',ub='gwt-dnd.css',nb='gwt.hybrid',ob='gwt/standard/standard.css',A='gwt:onLoadErrorFn',w='gwt:onPropertyErrorFn',t='gwt:property',tb='head',hb='hosted.html?avoir_realtime_base_gwt_Invite',sb='href',bb='ie6',xb='iframe',p='img',zb="javascript:''",pb='link',r='meta',gb='moduleRequested',ab='msie',s='name',D='opera',Ab='position:absolute;width:0;height:0;border:none',qb='rel',F='safari',yb='selectionDone',cb='selectionStart',x='startup',rb='stylesheet',fb='unknown',C='user.agent',E='webkit';var bc=window,k=document,jc=bc.external,ac=bc.__gwtstatsEvent?function(a,b,c,d){bc.__gwtstatsEvent(a,b,c,d)}:null,wc,mc,gc,fc=l,pc={},zc=[],vc=[],ec=[],sc,uc;ac&&ac(m,x,cb,{millis:(new Date()).getTime()});if(!bc.__gwt_stylesLoaded){bc.__gwt_stylesLoaded={}}if(!bc.__gwt_scriptsLoaded){bc.__gwt_scriptsLoaded={}}function lc(){try{return jc&&(jc.gwtOnLoad&&bc.location.search.indexOf(nb)==-1)}catch(a){return false}}
}
function oc(){if(wc&&mc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=avoir_realtime_base_gwt_Invite.__gwt_initHandlers;if(lc()){b.__gwt_getProperty=function(a){return hc(a)}}avoir_realtime_base_gwt_Invite=null;b.gwtOnLoad(sc,m,fc);ac&&ac(m,x,yb,{millis:(new Date()).getTime()})}}
function ic(){var j,h=Cb,i;k.write(Db+h+Eb);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=Fb){j=j.previousSibling}function d(b){var a=b.lastIndexOf(n);return a>=0?b.substring(0,a+1):l}
;if(j&&j.src){fc=d(j.src)}if(fc==l){var c=k.getElementsByTagName(o);if(c.length>0){fc=c[c.length-1].href}else{var g=k.location;var e=g.href;fc=d(e.substr(0,e.length-g.hash.length))}}else if(fc.match(/^\w+:\/\//)){}else{var f=k.createElement(p);f.src=fc+q;fc=d(f.src)}if(i){i.parentNode.removeChild(i)}}
function tc(){var f=document.getElementsByTagName(r);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(s),b;if(h){if(h==t){b=e.getAttribute(u);if(b){var i,c=b.indexOf(v);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}pc[h]=i}}else if(h==w){b=e.getAttribute(u);if(b){try{uc=eval(b)}catch(a){alert(y+b+z)}}}else if(h==A){b=e.getAttribute(u);if(b){try{sc=eval(b)}catch(a){alert(y+b+B)}}}}}}
function yc(d,e){var a=ec;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function hc(d){var e=vc[d](),b=zc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(uc){uc(d,a,e)}throw null}
vc[C]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(D)!=-1){return D}else if(d.indexOf(E)!=-1){return F}else if(d.indexOf(ab)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return bb}}}else if(d.indexOf(db)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return eb}return db}return fb};zc[C]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};avoir_realtime_base_gwt_Invite.onInjectionDone=function(){wc=true;ac&&ac(m,x,gb,{millis:(new Date()).getTime()});oc()};avoir_realtime_base_gwt_Invite.onScriptLoad=function(){if(kc){mc=true;oc()}};ic();tc();var xc;if(lc()){xc=hb}else{try{yc([bb],ib);yc([D],jb);yc([F],kb);yc([db],lb);yc([eb],mb);xc=ec[hc(C)]}catch(a){return}}var rc;function qc(){if(!gc){gc=true;if(!__gwt_stylesLoaded[ob]){var a=k.createElement(pb);__gwt_stylesLoaded[ob]=a;a.setAttribute(qb,rb);a.setAttribute(sb,fc+ob);k.getElementsByTagName(tb)[0].appendChild(a)}if(!__gwt_stylesLoaded[ub]){var a=k.createElement(pb);__gwt_stylesLoaded[ub]=a;a.setAttribute(qb,rb);a.setAttribute(sb,fc+ub);k.getElementsByTagName(tb)[0].appendChild(a)}if(!__gwt_stylesLoaded[vb]){var a=k.createElement(pb);__gwt_stylesLoaded[vb]=a;a.setAttribute(qb,rb);a.setAttribute(sb,fc+vb);k.getElementsByTagName(tb)[0].appendChild(a)}oc();if(k.removeEventListener){k.removeEventListener(wb,qc,false)}if(rc){clearInterval(rc)}}}
var kc;function nc(){if(!kc){kc=true;var a=k.createElement(xb);a.src=zb;a.id=m;a.style.cssText=Ab;a.tabIndex=-1;k.body.appendChild(a);a.contentWindow.location.replace(fc+xc)}}
if(k.addEventListener){k.addEventListener(wb,function(){nc();qc()},false)}var rc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){nc();qc()}},50);k.write(Bb)}
avoir_realtime_base_gwt_Invite.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a)}}};avoir_realtime_base_gwt_Invite();


*/