<?PHP

/*
 * This file was generated by the Web Parts Module Builder
 */

// Security Check - must be included in all scripts
if (!$GLOBALS['kewl_entry_point_run']) {
    die("You cannot view this page directly");
}
		
$tablename = 'tbl_libraryexams_users';

$options = array('collate' => 'latin1_swedish_ci','comment' => '');

$fields = array(


    'id' => array(
        'type' => 'text',
        'length' => 32
        ),
    'id' => array(
        'type' => 'integer',
        'length' => '',
        'notnull' => 'FALSE',
        'default' => '0000-00-00',
    ),
    'username' => array(
        'type' => 'text',
        'length' => '8',
        'notnull' => 'FALSE',
        'default' => '',
    ),
    'password' => array(
        'type' => 'text',
        'length' => '50',
        'notnull' => 'TRUE',
        'default' => '',
    ),
    'reg_date' => array(
        'type' => 'date',
        'notnull' => 'TRUE',
        'default' => '',
    ),
    'fullname' => array(
        'type' => 'text',
        'length' => '50',
        'notnull' => 'TRUE',
        'default' => '',
    )
);


//Generating Indexes

$name = 'idx_8d080aaaa3a21e3806dd5df05bffc910';
//Generating Indexes

$indexes = array(
             'fields' => array(
                'id' => array()
             )
);