<?PHP

/*
 * This file was generated by the Web Parts Module Builder
 */

// Security Check - must be included in all scripts
if (!$GLOBALS['kewl_entry_point_run']) {
    die("You cannot view this page directly");
}
		
$tablename = 'tbl_libraryexams_course_units';

$options = array('collate' => 'latin1_swedish_ci','comment' => '');

$fields = array(


    'id' => array(
        'type' => 'text',
        'length' => 32
        ),
    'new_m_code' => array(
        'type' => 'text',
        'length' => '10',
        'notnull' => 'FALSE',
        'default' => '',
    ),
    'old_m_code' => array(
        'type' => 'text',
        'length' => '10',
        'notnull' => 'FALSE',
        'default' => '',
    ),
    'm_name' => array(
        'type' => 'text',
        'length' => '250',
        'notnull' => 'TRUE',
        'default' => '',
    ),
    'd_code' => array(
        'type' => 'text',
        'length' => '10',
        'notnull' => 'TRUE',
        'default' => '',
    )
);


//Generating Indexes

$name = 'idx_a7e10163aab7f4e4c16b8f2226479958';
//Generating Indexes

$indexes = array(
             'fields' => array(
                'new_m_code' => array()
             )
);